### ISSUE TITLE
Dependencies for Python 3 and PyPy support

### ISSUE THREAD

**Issue by moreati** [Yubico/python-u2flib-host#11]
pthon-u2flib-host currently only Python 2.x (in particular CPython 2.x). The limiting factor is the required libraries. Porting python-u2flib-host would first require porting, or replacing
- [M2Crypto](https://github.com/martinpaljak/M2Crypto)
- [python-hidapi](https://github.com/trezor/cython-hidapi)

I'd like to propose M2Crypto be replaced, the project appears to be stalled (with no commits since May 2015) and it's written using SWIG which [isn't compatible with PyPy](https://bitbucket.org/pypy/compatibility/wiki/Home#!swig-swig). I'd like to propose [cryptography](https://github.com/pyca/cryptography)
- Apache/BSD dual licensed
- Supports Python 2.6-2.7, Python 3.3+ and PyPy
- Tested on Windows, Mac OSX and Linux
- Ships pre-built wheels for Python 32-bit and 64-bit on Windows
- Has multiple maintainers i.e. a bus factor > 1

I'm happy to do the work and provide a PR, but first I'd like to check you're happy with the concept. Would Yubico be willing to use cryptography instead of M2Crypto for python-u2flib-host?

**Comment by moreati** [comment]
Closely related to Yubico/python-u2flib-server#9

**Comment by dainnilsson** [comment]
I'd be very happy to swap out M2Crypto for Cryptography, in both host and server libraries. Last time I checked Cryptography wasn't quite up to the task (details in Yubico/python-u2flib-server#9), but things may have changed since then. I'm a bit hesitant to switch just one of the projects over if the other one can't be, for sake of consistency. Then again, maybe the benefits of switching are enough to motivate the inconsistency.

**Comment by moreati** [comment]
> I'm a bit hesitant to switch just one of the projects over if the other one can't be, for sake of consistency

I plan to do both

**Comment by moreati** [comment]
See https://github.com/moreati/python-u2flib-server/tree/cryptography for work in progress. Still relies on M2Crypto for certificate verification.

**Comment by moreati** [comment]
Time to resurrect this. I'll get a pull request together over the weekend, and maybe another for Python 3 support.

**Comment by dainnilsson** [comment]
Closing since the PR is merged.
