### ISSUE TITLE
u2flib_host.exc.APDUError: 0x6985

### ISSUE THREAD

**Issue by patatetom** [Yubico/python-u2flib-host#15]
hi,
with this code :
``` python
from u2flib_host import u2f
device = u2f.list_devices()
device = device.pop()
# next dictionary come from u2fval_client
registrationRequest = {u'challenge': u'-X0I9Cor1oh3ZoRff1F1h2cA_O9zeQtLMwIYXTMBHJo', u'version': u'U2F_V2', u'appId': u'https://localhost.localdomain'}
with device as yubikey:
 registrationResponse = u2f.register(yubikey, registrationRequest, 'https://localhost.localdomain')
```
I've this error :
```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/pascal/yubico/yubihost/lib/python2.7/site-packages/u2flib_host/u2f.py", line 63, in register
    return lib.register(device, data, facet)
  File "/home/pascal/yubico/yubihost/lib/python2.7/site-packages/u2flib_host/u2f_v2.py", line 70, in register
    response = device.send_apdu(INS_ENROLL, p1, p2, request)
  File "/home/pascal/yubico/yubihost/lib/python2.7/site-packages/u2flib_host/device.py", line 113, in send_apdu
    raise exc.APDUError(status)
u2flib_host.exc.APDUError: 0x6985
```
 and the yubikey blinks.
if I touch the yubikey (light is on) before calling u2f.register, a response is returned by the key (light is turned off) :
```python
with device as yubikey:
 registrationResponse = u2f.register(yubikey, registrationRequest, 'https://localhost.localdomain')
registrationResponse
{'registrationData': ..., 'clientData': ...}
```

**Comment by dainnilsson** [comment]
There's no question here, so I'm not quite sure what to do with this. You've correctly described the behavior, as it is intended to function. Feel free to re-open with a specific question if there is something that is unclear to you.

**Comment by patatetom** [comment]
indeed this is not a question but an observation :
without key preparation (untouched before calling the function), u2f.register() returns an error and the key flashes;
with key preparation (touched before calling the function), u2f.register() works without problems.

**Comment by dainnilsson** [comment]
U2F is designed as a non-blocking protocol, and each request must immediately return a response without delay. The intention is to periodically poll the device when touch is needed, sending the same request repeatedly until it returns successful (or a timeout is reached, and the operation is aborted). Thus, when the device is in an idle state and is touched, it will keep a user present state for a short period of time, and return a successful response to a request that comes within that time.

**Comment by patatetom** [comment]
thank you for this lighting.
