### ISSUE TITLE
hid_transport list_devices() method only returns the class name instead of an actual device object

### ISSUE THREAD

**Issue by stigbosmans** [Yubico/python-u2flib-host#20]
On line 71 in hid_transport.py only the following line is implemented:
`devices.append(HIDDevice)`
whereas I would expect that an object of the class HIDDevice would be implemented, like below:
`devices.append(HIDDevice(d['path']))`

Is there another way to obtain a list of actual HIDDevice objects? Or am I doing something wrong?

**Comment by dainnilsson** [comment]
That was fixed a while back (which you can see if you look at that line in the current code: 
https://github.com/Yubico/python-u2flib-host/blob/master/u2flib_host/hid_transport.py#L71)

There will be a new release which includes this fix shortly (probably some time next week), as well as some additional improvements, such as Python 3 compatibility.
