### ISSUE TITLE
Not actually compatible with python3

### ISSUE THREAD

**Issue by shuffle2** [Yubico/python-u2flib-host#21]
There are numerous things broken related to strings.

This line ( https://github.com/Yubico/python-u2flib-host/blob/master/u2flib_host/register.py#L98 ) will fail because str() (with an encoding) on something which is already a `str` raises a TypeError.

In the JSON parsing, all values are `bytes`. this causes lookups using strings to fail, like here: https://github.com/Yubico/python-u2flib-host/blob/master/u2flib_host/u2f.py#L58

**Comment by shuffle2** [comment]
Same type of issues with the get_version usb response, and probably some later code since it's still failing...


Is there a "production-ready" U2F lib? I am trying to use U2F as HTTP(S) Authentication (i.e. *not* after HTTP has been established), but I find myself spending a very large amount of time getting nothing done because nothing actually works, and U2F seems to not have been designed for these scenarios (just look at that SSH patch...still not implemented). pity. I'll probably give up and go with implementing some custom scheme. :(

**Comment by EugeneDae** [comment]
@shuffle2 +1 everything about U2F seems so half-baked and the documentation is very poor
