### ISSUE TITLE
communication between python-u2flib-host and python-u2flib-server

### ISSUE THREAD

**Issue by mqhh** [Yubico/python-u2flib-host#22]
I find that there is no code in this project sending data to the server. is it because that i'm not carefully enough, or that there is really no communication between the host and the server in this project, and we need to complete it?

**Comment by dainnilsson** [comment]
That's correct, the U2F specification does not define a protocol for client-to-server communication, it only specifies the message formats for use with U2F devices, and a high-level JavaScript API for interfacing with a FIDO client in a browser. How data moves between client and server are left up to the implementation.

Note that the JSON messages used for this project have not been updated for the 1.1 version of the FIDO U2F JavaScript API. This means that the JSON messages used require some adjustment to be used with the latest version of python-u2flib-server.

**Comment by mqhh** [comment]
Thank you very much! And may I ask where can i get a similar one which have been updated for the 1.1 version, or a project that can simulate communicating with a server.

**Comment by mqhh** [comment]
Thank you very much! And may I ask where can i get a similar one which have been updated for the 1.1 version, or a project that can simulate communicating with a server.

**Comment by dainnilsson** [comment]
I'm not aware of any host libraries which implement the 1.1 specification, but the changes are quite minimal:

> CHANGES: This version version 1.1 of the FIDO U2F JavaScript API specification supersedes version JavaScript API 1.0. The major difference between these two versions is the way that requests to be signed are formatted between the RP and the client: In version 1.0, a separate appId and challenge were sent for every keyHandle, whereas in version 1.1, an optimization is made that requires only a single appId and challenge for multiple keyHandles.

The specs are available here: https://fidoalliance.org/specs/fido-u2f-v1.1-id-20160915/fido-u2f-javascript-api-v1.1-id-20160915.html

As for communicating with a server, it really depends on the application. For example, in a browser setting the messages are commonly passed as part of a HTML page, including the code to interact with the JavaScript API.

**Comment by mqhh** [comment]
thank you. thank you very much.

**Comment by mqhh** [comment]
excuse me, there is another question. is u2f only used for registration and authentication? can i use it for transaction confirm?
