### ISSUE TITLE
u2f-register :command not found??!!

### ISSUE THREAD

**Issue by Jerry280989322** [Yubico/python-u2flib-host#31]
Hello~I have followed the steps given above,but when I run the command "u2f-register -s soft_device.json http://localhost:8081",the result is"u2f-register: command not found".I don't know how to solve it ?Can you help me ?

**Comment by jdtotow** [comment]
The command is u2f-host if your installation is correct.

**Comment by Jerry280989322** [comment]
emmmm.....it works after i  "pip install python-u2flib-host" in the root, but i don't know why.....
I have tried as whtat you said ,but it reminds me that "u2f-host" is not currently installed.

**Comment by Jerry280989322** [comment]
@jdtotow
