### ISSUE TITLE
How to add rules into rules.d? I don't know the detailed steps.Can you help me?

### ISSUE THREAD

**Issue by Jerry280989322** [Yubico/python-u2flib-host#32]

**Comment by dainnilsson** [comment]
The easiest approach is to install the package libu2f-udev, available for Debian and Ubuntu.
You can also install the udev rules available here: https://github.com/Yubico/libu2f-host/blob/master/70-u2f.rules

Refer to documentation on using Udev for your Linux distribution for instructions.
