### ISSUE TITLE
Wrong U2F Command parameter when U2F_REGISTER

### ISSUE THREAD

**Issue by HWataru** [Yubico/python-u2flib-host#34]
In [U2F spec](https://fidoalliance.org/specs/fido-u2f-v1.2-ps-20170411/fido-u2f-raw-message-formats-v1.2-ps-20170411.html) U2F_REGISTER command parameter define P1 => 0x00, P2 => 0x00. But this code P1 => 0x03, P2 => 0x00. 

https://github.com/Yubico/python-u2flib-host/blob/7431bd115befdd4ad1a5a6e68ed0c2da05b95c46/u2flib_host/u2f_v2.py#L71-L73

Nevertheless YubiKey work fine...

**Comment by dainnilsson** [comment]
p1 is deliberately set to 0x03 for compatibility with some older devices. As this does not cause any problem with any known devices, this will be left as-is. If it is determined that this is causing trouble with some devices we may open this up again.
