### ISSUE TITLE
Document what versions of Python are supported

### ISSUE THREAD

**Issue by moreati** [Yubico/python-u2flib-host#5]
From the use of argparse in the scripts I infer only Python 2.7 (and possibly 3.2+) is supported, but that may be a bug.

 - What 2.x versions of Python does this package officially support?
 - Would you be interested in a patch to support Python 2.6?

Let me know the answer and I'll submit a pull request to document it, and if necessary fix missing 2.6 support.

**Comment by dainnilsson** [comment]
We've only targeted 2.7 during development. I suppose we could consider maintaining 2.6 compatibility if there is a need for it. Honestly I think supporting 3.x is more worthwhile. Do you personally need 2.6 compatibility for any reason? I'm leaving on vacation for 4 weeks, so I apologize in advance if I'm not very active in this discussion for a while.

**Comment by moreati** [comment]
No, I don't need 2.6 compatibility. Thanks for clarifying.
