### ISSUE TITLE
Scripts still contain GPL license header

### ISSUE THREAD

**Issue by moreati** [Yubico/python-u2flib-host#6]
Since d89ef7e277d99b4c1ba616c44c917edd7f84d7b5 changed the license to BSD, the 2 scripts still contain a GPL licence header e.g. [u2f-authenticate](https://github.com/Yubico/python-u2flib-host/blob/520ae959f78992c832079f546463238888e31447/scripts/u2f-authenticate)

Is this intentional?

**Comment by dainnilsson** [comment]
It is not, thanks for pointing this out. I'll push a change that fixes this right away.
